server:
  port: 9092

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false
  jackson:
    time-zone: UTC

logging:
  level:
    root: WARN
    com.analysis: INFO